ext: Sync `ext-libfdt` with dtc v1.7.2 (#3037)
Clang 21 introduces `-Wtautological-compare`, which causes our 2013-era
`libfdt` snapshot to fail because it tries to spot overflow with `if (p
+ len < p)` pointer arithmetic (see here:
https://github.com/gem5/gem5/blob/7a2b0e413d06c5ce7097104abef3b1d9eaabca91/ext/libfdt/fdt.c#L67).
The warning/error returned is:

```
 [ SHCC] ext/libfdt/fdt_ro.c -> ALL/ext/libfdt/fdt_ro.os
ext/libfdt/fdt.c:67:21: error: pointer comparison always evaluates to false
 [-Werror,-Wtautological-compare]
```

This change refreshes `ext/libfdt` to the version shipped with the
lastest releast of dtc - v1.7.2. The newer code performs its bounds
checking in integer space, so the new clang warning goes away while
keeping the same behaviour.